default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: has_many_development

test:
  <<: *default
  database: has_many_test

production:
  <<: *default
  database: has_many_production
  username: has_many
  password: <%= ENV['HAS_MANY_DATABASE_PASSWORD'] %>
